CREATE DATABASE QUANLYBANHANG;
USE QUANLYBANHANG;
CREATE TABLE CUSTOMER(
	cID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    cName VARCHAR(30),
    cAge INT CHECK (cAge >=18)
);

CREATE TABLE ORDERS(
	oID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    cID INT,
    oDate DATETIME,
    oTatalPrice BIGINT,
    FOREIGN KEY (cID) REFERENCES CUSTOMER(cID)
);

CREATE TABLE PRODUCT(
	pID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    pNAME VARCHAR(30),
    pPRICE BIGINT
);

CREATE TABLE ORDERDETAIL(
	oID INT,
    pID INT,
    odQTY INT,
    UNIQUE (oID,pID),
    FOREIGN KEY (oID) REFERENCES ORDERS (oID),
    FOREIGN KEY (pID) REFERENCES PRODUCT (pID)
);