CREATE DATABASE QUANLYSINHVIEN;
USE QUANLYSINHVIEN;
CREATE TABLE CLASS(
	ClassID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ClassName VARCHAR(60),
    StartDate DATETIME NOT NULL,
    Status BIT
);

CREATE TABLE STUDENT(
	StudentID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    StudentName VARCHAR(30) NOT NULL,
    Address VARCHAR(50),
    Phone VARCHAR(20),
    Status BIT,
    ClassID INT NOT NULL,
    FOREIGN KEY (ClassID) REFERENCES CLASS(ClassID)
);

CREATE TABLE SUBJECT_SCHOOL(
	SubID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SubName VARCHAR(30) NOT NULL,
    Credit TINYINT NOT NULL DEFAULT 1,
    Status BIT DEFAULT 1,
    CHECK (CREDIT >=1)
);

CREATE TABLE MARK(
	MarkID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SubId INT,
    StudentID INT,
    Mark FLOAT DEFAULT 0 CHECK (MARK BETWEEN 0 AND 100),
    ExamTimes TINYINT DEFAULT 1,
    UNIQUE (SubID,StudentID),
    FOREIGN KEY (SubID) REFERENCES SUBJECT_SCHOOL (SubID),
    FOREIGN KEY (StudentID) REFERENCES STUDENT (StudentID)
);