CREATE DATABASE QUANLYDIEMTHI;
USE QUANLYDIEMTHI;
CREATE TABLE HOCSINH(
	MaHS VARCHAR(20) PRIMARY KEY,
    TenHS VARCHAR(50),
    NgaySinh DATETIME,
    Lop VARCHAR(20),
    GT VARCHAR(20)
);

CREATE TABLE MONHOC(
	MaMH VARCHAR(20) PRIMARY KEY,
    TenMH VARCHAR(50)
);
CREATE TABLE BANGDIEMT(
	MaHS VARCHAR(20),
    MaMH VARCHAR(20),
    DiemThi INT,
    NgayKT DATETIME,
    FOREIGN KEY (MaHS) REFERENCES HOCSINH (MaHS),
    FOREIGN KEY (MaMH) REFERENCES MONHOC (MaMH)
);

CREATE TABLE GIAOVIEN(
	MaGV VARCHAR(20) PRIMARY KEY,
    TenGV VARCHAR(50),
    SDT VARCHAR(10)
);

ALTER TABLE MONHOC ADD MaGV VARCHAR(20);
ALTER TABLE MONHOC ADD CONSTRAINT FK_MaGV FOREIGN KEY (MaGV) REFERENCES GIAOVIEN(MaGV);