CREATE DATABASE SHOPPE;
USE SHOPPE;

CREATE TABLE CATEGORY (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    cName VARCHAR(50)
);

CREATE TABLE PRODUCT (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    pName VARCHAR(50),
    price BIGINT,
    cID INT,
	FOREIGN KEY (cID) REFERENCES CATEGORY (ID)
);

CREATE TABLE VARIAT (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    size INT,
    color VARCHAR(30),
    pID INT,
    FOREIGN KEY (pID) REFERENCES PRODUCT (ID)
);

CREATE TABLE USERS (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(50) UNIQUE,
    uPassword VARCHAR(50)
);

CREATE TABLE CART(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    total BIGINT,
    users_ID INT UNIQUE,
    FOREIGN KEY (users_ID) REFERENCES USERS(ID)
);

CREATE TABLE CARTLINE (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	quantity int,
    price BIGINT,
	subTotal BIGINT,
    product_ID INT,
    cart_ID INT,
    variat_ID INT,
    FOREIGN KEY (product_ID) REFERENCES PRODUCT (ID),
    FOREIGN KEY (cart_ID) REFERENCES CART (ID),
    FOREIGN KEY (variat_ID) REFERENCES VARIAT (ID)
);

CREATE TABLE ORDERS (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	total BIGINT,
    users_ID INT UNIQUE,
    FOREIGN KEY (users_ID) REFERENCES USERS(ID)
);

CREATE TABLE ORDERSLINE (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	quantity int,
    price BIGINT,
	subTotal BIGINT,
    dayPlay DATETIME,
    addressFrom VARCHAR(100),
    product_ID INT,
    orders_ID INT,
	variat_ID INT,
    FOREIGN KEY (product_ID) REFERENCES PRODUCT (ID),
    FOREIGN KEY (orders_ID) REFERENCES ORDERS (ID),
    FOREIGN KEY (variat_ID) REFERENCES VARIAT (ID)
);