CREATE DATABASE SHOPPE;
USE SHOPPE;
DROP DATABASE SHOPPE;
CREATE TABLE USERS (
	uID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    firstName VARCHAR(20) NOT NULL,
    lastName VARCHAR(30),
    email VARCHAR(60) UNIQUE,
    phone VARCHAR(10) UNIQUE,
    age INT,
    nationality VARCHAR(100) DEFAULT 'VIETNAMESE'
);
ALTER TABLE USERS ADD CHECK (AGE>=18);



CREATE TABLE CATEGORY(
	cID INT,
    cName VARCHAR(50)
);
ALTER TABLE CATEGORY ADD PRIMARY KEY (cID);

CREATE TABLE PRODUCTS(
	pID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    pNAME VARCHAR(100),
    pPrice BIGINT,
    pDescribe TEXT,
    cID INT NOT NULL

);
ALTER TABLE PRODUCTS ADD FOREIGN KEY (cID) REFERENCES CATEGORY (cID);

CREATE TABLE CARD (
	caID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    total BIGINT,
    uID INT NOT NULL,
    FOREIGN KEY (uID) REFERENCES USERS (uID)
);

CREATE TABLE CARDLINE (
	lineID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    lineQuantity INT DEFAULT 1,
    price BIGINT UNIQUE,
    subTotal BIGINT,
    pID INT NOT NULL,
    FOREIGN KEY (pID) REFERENCES PRODUCTS (pID)
);

INSERT INTO USERS (firstName,lastName,email,phone,age,nationality) VALUES
('Tien','Q12','tien@gmail.com','0912313411',35,'LAO'),
('Hai','Tac','hai@gmail.com','0912313412',18,'THAI'),
('Hai','Cu chi','haiC3@gmail.com','0912313413',26,'CHINA')
;

SELECT * FROM USERS;SELECT * FROM USERS;

UPDATE USERS SET EMAIL = 'haiGV' WHERE ID=3;

DELETE FROM USERS WHERE firstName = 'Tien';

SELECT * FROM USERS WHERE age >=20;
SELECT * FROM USERS WHERE firstName LIKE 'H%';
SELECT * FROM USERS WHERE age BETWEEN 20 AND 40;
SELECT * FROM USERS WHERE nationality IN ('LAO','THAI');
